name: CI

on:
  - push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  single-location:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [macOS-latest]
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: duplicate coverage result
        run: npm coverage && cp ${{github.workspace}}/coverage/lcov.info ${{github.workspace}}/coverage/lcov2.info
      - name: Coverage to Codeclimate
        uses: MartinNuc/codeclimate-action@2
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
            ${{github.workspace}}/coverage/lcov2.info:lcov
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Install dependencies
#         run: yarn install --frozen-lockfile    
#       - name: Coverage to Codeclimate
#         uses: MartinNuc/codeclimate-action@2
#         env:
#           CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
#         with:
#           coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
          

