name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build
        # Install and build project
        run: |
          make install
        # Add environment variables
        env:
          CI: true
      - name: Test & publish code coverage
        run: |
          make test-coverage
#       - name: Upload coverage to Codecov
#           uses: codecov/codecov-action@v1
#           with:
#             token: ${{ secrets.CODECOV_TOKEN }}

