name: CI

on:
  - push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # Check-out repository under GitHub workspace
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Use Node.js ${{ matrix.node-version }}
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        # The Node.js version to configure
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: npm install, build
        # Install and build project
        run: |
          make install
        # Add environment variables
        env:
          CI: true
          
      - name: Test & publish code coverage
        run: |
          make test-coverage
          
#       - name: Upload coverage to Codecov
#           uses: codecov/codecov-action@v1
#           with:
#             token: ${{ secrets.CODECOV_TOKEN }}

